# Generated by Django 5.1.7 on 2025-03-27 08:27

from django.db import migrations

def create_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    # Delete any existing sites
    Site.objects.all().delete()
    # Create new site with ID=1
    Site.objects.create(
        id=1,
        domain='127.0.0.1:8000',
        name='Cooked Website'
    )

class Migration(migrations.Migration):
    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(create_site),
    ]
