# Generated by Django 5.1.7 on 2025-03-10 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipetype', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='recipename',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipetype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.recipetype'),
        ),
    ]
