# Generated by Django 5.1.7 on 2025-03-10 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipetype_rename_name_recipe_recipename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='madeby',
            field=models.CharField(default='Firstname Lastname', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.recipetype'),
        ),
    ]
