# Generated by Django 5.1.7 on 2025-03-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_savedrecipe_recipe_remove_savedrecipe_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
