# Generated by Django 5.1.7 on 2025-03-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_madeby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='madeby',
            field=models.CharField(max_length=50),
        ),
    ]
