# Generated by Django 5.1.7 on 2025-03-28 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(default=0, help_text='Cooking time in minutes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(default=0, help_text='Preparation time in minutes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=1, help_text='Number of servings'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'recipe')},
        ),
    ]
