# Generated by Django 5.1.7 on 2025-03-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_recipe_cook_time_recipe_prep_time_recipe_servings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(),
        ),
    ]
